using System;
using System.Collections.Generic;

namespace RegistryExpert.Core
{
    /// <summary>
    /// Built-in dictionary mapping Windows service names to their display names.
    /// Used for offline hive analysis where MUI string resolution is not available.
    /// </summary>
    public static class ServiceDisplayNameLookup
    {
        private static readonly Dictionary<string, string> _map =
            new(StringComparer.OrdinalIgnoreCase)
        {
            ["AarSvc"] = "Agent Activation Runtime",
            ["AJRouter"] = "AllJoyn Router Service",
            ["ALG"] = "Application Layer Gateway Service",
            ["AppIDSvc"] = "Application Identity",
            ["Appinfo"] = "Application Information",
            ["AppMgmt"] = "Application Management",
            ["AppReadiness"] = "App Readiness",
            ["AppVClient"] = "Microsoft App-V Client",
            ["AppXSvc"] = "AppX Deployment Service (AppXSVC)",
            ["AssignedAccessManagerSvc"] = "AssignedAccessManager Service",
            ["AudioEndpointBuilder"] = "Windows Audio Endpoint Builder",
            ["Audiosrv"] = "Windows Audio",
            ["autotimesvc"] = "Cellular Time",
            ["AxInstSV"] = "ActiveX Installer (AxInstSV)",
            ["BcastDVRUserService"] = "GameDVR and Broadcast User Service",
            ["BDESVC"] = "BitLocker Drive Encryption Service",
            ["BFE"] = "Base Filtering Engine",
            ["BITS"] = "Background Intelligent Transfer Service",
            ["BluetoothUserService"] = "Bluetooth User Support Service",
            ["BrokerInfrastructure"] = "Background Tasks Infrastructure Service",
            ["BTAGService"] = "Bluetooth Audio Gateway Service",
            ["BthAvctpSvc"] = "AVCTP service",
            ["bthserv"] = "Bluetooth Support Service",
            ["camsvc"] = "Capability Access Manager Service",
            ["CaptureService"] = "Capture Service",
            ["cbdhsvc"] = "Clipboard User Service",
            ["CDPSvc"] = "Connected Devices Platform Service",
            ["CDPUserSvc"] = "Connected Devices Platform User Service",
            ["CertPropSvc"] = "Certificate Propagation",
            ["ClipSVC"] = "Client License Service (ClipSVC)",
            ["CloudBackupRestoreSvc"] = "Cloud Backup and Restore Service",
            ["cloudidsvc"] = "Microsoft Cloud Identity Service",
            ["COMSysApp"] = "COM+ System Application",
            ["ConsentUxUserSvc"] = "ConsentUX User Service",
            ["CoreMessagingRegistrar"] = "CoreMessaging",
            ["CredentialEnrollmentManagerUserSvc"] = "Credential Enrollment Manager User Service",
            ["CryptSvc"] = "Cryptographic Services",
            ["CscService"] = "Offline Files",
            ["DcomLaunch"] = "DCOM Server Process Launcher",
            ["dcsvc"] = "Declared Configuration (DC) Service",
            ["defragsvc"] = "Optimize Drives",
            ["DeviceAssociationBrokerSvc"] = "Device Association Broker",
            ["DeviceAssociationService"] = "Device Association Service",
            ["DeviceInstall"] = "Device Install Service",
            ["DevicePickerUserSvc"] = "Device Picker",
            ["DevicesFlowUserSvc"] = "Devices Flow",
            ["DevQueryBroker"] = "DevQuery Background Discovery Broker",
            ["Dhcp"] = "DHCP Client",
            ["diagsvc"] = "Diagnostic Execution Service",
            ["DiagTrack"] = "Connected User Experiences and Telemetry",
            ["DialogBlockingService"] = "Dialog Blocking Service",
            ["DispBrokerDesktopSvc"] = "Display Policy Service",
            ["DisplayEnhancementService"] = "Display Enhancement Service",
            ["DmEnrollmentSvc"] = "Device Management Enrollment Service",
            ["dmwappushservice"] = "Device Management WAP Push Message Routing Service",
            ["Dnscache"] = "DNS Client",
            ["DoSvc"] = "Delivery Optimization",
            ["dot3svc"] = "Wired AutoConfig",
            ["DPS"] = "Diagnostic Policy Service",
            ["DsmSvc"] = "Device Setup Manager",
            ["DsSvc"] = "Data Sharing Service",
            ["DusmSvc"] = "Data Usage",
            ["EapHost"] = "Extensible Authentication Protocol",
            ["EFS"] = "Encrypting File System (EFS)",
            ["embeddedmode"] = "Embedded Mode",
            ["EntAppSvc"] = "Enterprise App Management Service",
            ["EventLog"] = "Windows Event Log",
            ["EventSystem"] = "COM+ Event System",
            ["fdPHost"] = "Function Discovery Provider Host",
            ["FDResPub"] = "Function Discovery Resource Publication",
            ["fhsvc"] = "File History Service",
            ["FontCache"] = "Windows Font Cache Service",
            ["FrameServer"] = "Windows Camera Frame Server",
            ["FrameServerMonitor"] = "Windows Camera Frame Server Monitor",
            ["GameInputSvc"] = "GameInput Service",
            ["gpsvc"] = "Group Policy Client",
            ["GraphicsPerfSvc"] = "Graphics Performance Monitor Service",
            ["hidserv"] = "Human Interface Device Service",
            ["HvHost"] = "HV Host Service",
            ["icssvc"] = "Windows Mobile Hotspot Service",
            ["IKEEXT"] = "IKE and AuthIP IPsec Keying Modules",
            ["InstallService"] = "Microsoft Store Install Service",
            ["InventorySvc"] = "Inventory and Compatibility Appraisal Service",
            ["iphlpsvc"] = "IP Helper",
            ["IpxlatCfgSvc"] = "IP Translation Configuration Service",
            ["KeyIso"] = "CNG Key Isolation",
            ["KtmRm"] = "KtmRm for Distributed Transaction Coordinator",
            ["LanmanServer"] = "Server",
            ["LanmanWorkstation"] = "Workstation",
            ["lfsvc"] = "Geolocation Service",
            ["LicenseManager"] = "Windows License Manager Service",
            ["lltdsvc"] = "Link-Layer Topology Discovery Mapper",
            ["lmhosts"] = "TCP/IP NetBIOS Helper",
            ["LocalKdc"] = "Kerberos Local Key Distribution Center",
            ["LSM"] = "Local Session Manager",
            ["LxpSvc"] = "Language Experience Service",
            ["MapsBroker"] = "Downloaded Maps Manager",
            ["McmSvc"] = "Mobile Connectivity Management Service",
            ["MDCoreSvc"] = "Microsoft Defender Core Service",
            ["MessagingService"] = "Messaging Service",
            ["midisrv"] = "Windows MIDI Service",
            ["mpssvc"] = "Windows Defender Firewall",
            ["MSDTC"] = "Distributed Transaction Coordinator",
            ["MSiSCSI"] = "Microsoft iSCSI Initiator Service",
            ["msiserver"] = "Windows Installer",
            ["MsKeyboardFilter"] = "Microsoft Keyboard Filter",
            ["NaturalAuthentication"] = "Natural Authentication",
            ["NcaSvc"] = "Network Connectivity Assistant",
            ["NcbService"] = "Network Connection Broker",
            ["NcdAutoSetup"] = "Network Connected Devices Auto-Setup",
            ["Netlogon"] = "Netlogon",
            ["Netman"] = "Network Connections",
            ["netprofm"] = "Network List Service",
            ["NetSetupSvc"] = "Network Setup Service",
            ["NetTcpPortSharing"] = "Net.Tcp Port Sharing Service",
            ["NgcCtnrSvc"] = "Microsoft Passport Container",
            ["NgcSvc"] = "Microsoft Passport",
            ["NlaSvc"] = "Network Location Awareness",
            ["NPSMSvc"] = "Now Playing Session Manager Service",
            ["nsi"] = "Network Store Interface Service",
            ["OneSyncSvc"] = "Sync Host",
            ["P9RdrService"] = "Plan 9 File System Redirector",
            ["PcaSvc"] = "Program Compatibility Assistant Service",
            ["PeerDistSvc"] = "BranchCache",
            ["PenService"] = "Pen Service",
            ["perceptionsimulation"] = "Windows Perception Simulation Service",
            ["PerfHost"] = "Performance Counter DLL Host",
            ["PhoneSvc"] = "Phone Service",
            ["PimIndexMaintenanceSvc"] = "Contact Data",
            ["pla"] = "Performance Logs & Alerts",
            ["PlugPlay"] = "Plug and Play",
            ["PolicyAgent"] = "IPsec Policy Agent",
            ["Power"] = "Power",
            ["PrintDeviceConfigurationService"] = "Print Device Configuration Service",
            ["PrintNotify"] = "Printer Extensions and Notifications",
            ["PrintScanBrokerService"] = "Print Scan Broker Service",
            ["PrintWorkflowUserSvc"] = "Print Workflow",
            ["ProfSvc"] = "User Profile Service",
            ["PushToInstall"] = "Windows PushToInstall Service",
            ["QWAVE"] = "Quality Windows Audio Video Experience",
            ["RasAuto"] = "Remote Access Auto Connection Manager",
            ["RasMan"] = "Remote Access Connection Manager",
            ["RdAgent"] = "Remote Desktop Agent",
            ["RDAgentBootLoader"] = "Remote Desktop Agent Loader",
            ["refsdedupsvc"] = "ReFS Dedup Service",
            ["RemoteAccess"] = "Routing and Remote Access",
            ["RemoteRegistry"] = "Remote Registry",
            ["RetailDemo"] = "Retail Demo Service",
            ["RmSvc"] = "Radio Management Service",
            ["RpcEptMapper"] = "RPC Endpoint Mapper",
            ["RpcLocator"] = "Remote Procedure Call (RPC) Locator",
            ["RpcSs"] = "Remote Procedure Call (RPC)",
            ["sacsvr"] = "Special Administration Console Helper",
            ["SamSs"] = "Security Accounts Manager",
            ["SCardSvr"] = "Smart Card",
            ["ScDeviceEnum"] = "Smart Card Device Enumeration Service",
            ["Schedule"] = "Task Scheduler",
            ["SCPolicySvc"] = "Smart Card Removal Policy",
            ["SDRSVC"] = "Windows Backup",
            ["seclogon"] = "Secondary Logon",
            ["SecurityHealthService"] = "Windows Security Service",
            ["SEMgrSvc"] = "Payments and NFC/SE Manager",
            ["SENS"] = "System Event Notification Service",
            ["Sense"] = "Windows Defender Advanced Threat Protection Service",
            ["SensorDataService"] = "Sensor Data Service",
            ["SensorService"] = "Sensor Service",
            ["SensrSvc"] = "Sensor Monitoring Service",
            ["SessionEnv"] = "Remote Desktop Configuration",
            ["SharedAccess"] = "Internet Connection Sharing (ICS)",
            ["ShellHWDetection"] = "Shell Hardware Detection",
            ["shpamsvc"] = "Shared PC Account Manager",
            ["smphost"] = "Microsoft Storage Spaces SMP",
            ["SmsRouter"] = "Microsoft Windows SMS Router Service",
            ["SNMPTrap"] = "SNMP Trap",
            ["Spooler"] = "Print Spooler",
            ["sppsvc"] = "Software Protection",
            ["SSDPSRV"] = "SSDP Discovery",
            ["ssh-agent"] = "OpenSSH Authentication Agent",
            ["sshd"] = "OpenSSH SSH Server",
            ["SstpSvc"] = "Secure Socket Tunneling Protocol Service",
            ["StateRepository"] = "State Repository Service",
            ["StiSvc"] = "Windows Image Acquisition (WIA)",
            ["StorSvc"] = "Storage Service",
            ["svsvc"] = "Spot Verifier",
            ["swprv"] = "Microsoft Software Shadow Copy Provider",
            ["SysMain"] = "SysMain",
            ["SystemEventsBroker"] = "System Events Broker",
            ["TapiSrv"] = "Telephony",
            ["TermService"] = "Remote Desktop Services",
            ["TextInputManagementService"] = "Text Input Management Service",
            ["Themes"] = "Themes",
            ["TieringEngineService"] = "Storage Tiers Management",
            ["TimeBrokerSvc"] = "Time Broker",
            ["TokenBroker"] = "Web Account Manager",
            ["TrkWks"] = "Distributed Link Tracking Client",
            ["TroubleshootingSvc"] = "Recommended Troubleshooting Service",
            ["TrustedInstaller"] = "Windows Modules Installer",
            ["tzautoupdate"] = "Auto Time Zone Updater",
            ["UdkUserSvc"] = "Udk User Service",
            ["UevAgentService"] = "User Experience Virtualization Service",
            ["UmRdpService"] = "Remote Desktop Services UserMode Port Redirector",
            ["UnistoreSvc"] = "User Data Storage",
            ["upnphost"] = "UPnP Device Host",
            ["UserDataSvc"] = "User Data Access",
            ["UserManager"] = "User Manager",
            ["UsoSvc"] = "Update Orchestrator Service",
            ["VaultSvc"] = "Credential Manager",
            ["vds"] = "Virtual Disk",
            ["vmicguestinterface"] = "Hyper-V Guest Service Interface",
            ["vmicheartbeat"] = "Hyper-V Heartbeat Service",
            ["vmickvpexchange"] = "Hyper-V Data Exchange Service",
            ["vmicrdv"] = "Hyper-V Remote Desktop Virtualization Service",
            ["vmicshutdown"] = "Hyper-V Guest Shutdown Service",
            ["vmictimesync"] = "Hyper-V Time Synchronization Service",
            ["vmicvmsession"] = "Hyper-V PowerShell Direct Service",
            ["vmicvss"] = "Hyper-V Volume Shadow Copy Requestor",
            ["VSS"] = "Volume Shadow Copy",
            ["W32Time"] = "Windows Time",
            ["WaaSMedicSvc"] = "Windows Update Medic Service",
            ["WalletService"] = "Wallet Service",
            ["WarpJITSvc"] = "Warp JIT Service",
            ["wbengine"] = "Block Level Backup Engine Service",
            ["WbioSrvc"] = "Windows Biometric Service",
            ["Wcmsvc"] = "Windows Connection Manager",
            ["wcncsvc"] = "Windows Connect Now - Config Registrar",
            ["WdiServiceHost"] = "Diagnostic Service Host",
            ["WdiSystemHost"] = "Diagnostic System Host",
            ["WdNisSvc"] = "Microsoft Defender Antivirus Network Inspection Service",
            ["WebClient"] = "WebClient",
            ["webthreatdefsvc"] = "Web Threat Defense Service",
            ["webthreatdefusersvc"] = "Web Threat Defense User Service",
            ["Wecsvc"] = "Windows Event Collector",
            ["WEPHOSTSVC"] = "Windows Encryption Provider Host Service",
            ["wercplsupport"] = "Problem Reports Control Panel Support",
            ["WerSvc"] = "Windows Error Reporting Service",
            ["WFDSConMgrSvc"] = "Wi-Fi Direct Services Connection Manager Service",
            ["whesvc"] = "Windows Health and Optimized Experiences",
            ["WiaRpc"] = "Still Image Acquisition Events",
            ["WinDefend"] = "Microsoft Defender Antivirus Service",
            ["WinHttpAutoProxySvc"] = "WinHTTP Web Proxy Auto-Discovery Service",
            ["Winmgmt"] = "Windows Management Instrumentation",
            ["WinRM"] = "Windows Remote Management (WS-Management)",
            ["wisvc"] = "Windows Insider Service",
            ["WlanSvc"] = "WLAN AutoConfig",
            ["wlidsvc"] = "Microsoft Account Sign-in Assistant",
            ["wlpasvc"] = "Local Profile Assistant Service",
            ["WManSvc"] = "Windows Management Service",
            ["wmiApSrv"] = "WMI Performance Adapter",
            ["WMPNetworkSvc"] = "Windows Media Player Network Sharing Service",
            ["workfolderssvc"] = "Work Folders",
            ["WpcMonSvc"] = "Parental Controls",
            ["WPDBusEnum"] = "Portable Device Enumerator Service",
            ["WpnService"] = "Windows Push Notifications System Service",
            ["WpnUserService"] = "Windows Push Notifications User Service",
            ["wscsvc"] = "Security Center",
            ["WSearch"] = "Windows Search",
            ["wuauserv"] = "Windows Update",
            ["wuqisvc"] = "Microsoft Usage and Quality Insights",
            ["WwanSvc"] = "WWAN AutoConfig",
            ["XblAuthManager"] = "Xbox Live Auth Manager",
            ["XblGameSave"] = "Xbox Live Game Save",
            ["XboxGipSvc"] = "Xbox Accessory Management Service",
            ["XboxNetApiSvc"] = "Xbox Live Networking Service",
            // Additional well-known services
            ["ADPSvc"] = "Aggregated Data Platform Service",
            ["ApxSvc"] = "Windows Virtual Audio Device Proxy Service",
            ["hpatchmon"] = "Hotpatch Monitoring Service",
            ["WindowsAzureGuestAgent"] = "Windows Azure Guest Agent",
            ["edgeupdate"] = "Microsoft Edge Update Service",
            ["edgeupdatem"] = "Microsoft Edge Update Service (Manual)",
            ["MicrosoftEdgeElevationService"] = "Microsoft Edge Elevation Service",
        };

        /// <summary>
        /// Resolves a service name to its display name.
        /// Returns the raw <paramref name="rawDisplayName"/> if not found in the lookup,
        /// stripping MUI string references (e.g., "@%systemroot%\...,-123") to just the service name.
        /// </summary>
        public static string Resolve(string serviceName, string? rawDisplayName = null)
        {
            if (_map.TryGetValue(serviceName, out var displayName))
                return displayName;

            // If the raw display name is a MUI reference, fall back to the service name
            if (string.IsNullOrEmpty(rawDisplayName) || rawDisplayName.StartsWith("@"))
                return serviceName;

            return rawDisplayName;
        }
    }
}
